permissions:
  checks: write
  contents: write

name: mvn
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: mvn test
      run: mvn -B test
    - name: junit report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/surefire-reports/TEST-*.xml'
    - name: dependency report
      uses: advanced-security/maven-dependency-submission-action@v3
